- name: Get status of /var/root
  stat:
    path: /var/root
  register: status_var_root
  tags: fs

- name: Move /root in /var/root
  command: "{{ item }}"
  with_items:
    - mv /root /var/root
    - ln -s var/root /root
  when: not status_var_root.stat.exists
  tags: fs

- name: Get status of /var/home
  stat:
    path: /var/home
  register: status_var_home
  tags: fs

- name: Move /home in /var/home
  command: "{{ item }}"
  with_items:
    - mv /home /var/home
    - ln -s var/home /home
  when: not status_var_home.stat.exists
  tags: fs

- name: install vimrc.local
  template:
    src: vimrc.local.j2
    dest: /etc/vim/vimrc.local
  tags: vim

- name: install /root/.vimrc
  template:
    src: root_dotvimrc.j2
    dest: /root/.vimrc
  tags: vim

- name: configure sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  tags: apt

- name: configure to keep deb files in archive
  template:
    src: 01keep-debs.j2
    dest: /etc/apt/apt.conf.d/01keep-debs
  tags: apt

- name: install ssh_config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
  tags: ssh
